language: python

os: ubuntu

services:
  - docker

before_install:
  - cd docker-dev
  - docker build -t underworld .
  - docker run underworld /bin/bash -c "pip3 install pytest; cp -rf /opt/UWGeodynamics /workspace; cd /workspace/UWGeodynamics; python -m pytest -v"

