
version: '3.7' 
services:     
    underworld:
        container_name: UWGeodynamics
        image: underworldcode/uwgeodynamics:2.9.4
        build:
          context: $PWD
          dockerfile: Dockerfile
        hostname: "uw-container"
        volumes:
          - $PWD/UWGeodynamics:/opt/venv/lib/python3.7/site-packages/UWGeodynamics  
          - $PWD/examples:/workspace/user_data/examples
          - $PWD/tutorials:/workspace/user_data/tutorials
          - $PWD/benchmarks:/workspace/user_data/benchmarks
        working_dir: /workspace/user_data
        command: "jupyter notebook --ip=0.0.0.0 --no-browser"
        ports:
          - "8888:8888"
          - "9999:9999"        

