
version: '3.7' 
services:     
    underworld:
        container_name: UWGeodynamics-dev
        image: underworldcode/uwgeodynamics:dev
        build:
          context: $PWD
          dockerfile: Dockerfile
        hostname: "uw-container"
        volumes:
          - $PWD:/opt/UWGeodynamics  
          - $PWD/examples:/workspace/user_data/examples
          - $PWD/tutorials:/workspace/user_data/tutorials
          - $HOME/Projects:/workspace/user_data/Projects
          - $HOME/Dropbox/MELBOURNE/MODELS:/workspace/user_data/models
        working_dir: /workspace/user_data
        command: "jupyter notebook --ip=0.0.0.0 --no-browser"
        ports:
          - "8888:8888"
          - "9999:9999"        

