
name: Docker
on: [push]

jobs:
  build:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: underworldcode/uwgeodynamics
          tag_with_ref: true
          tag_with_sha: true