name: Build on Gadi
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: source /scratch/q97/codes/setup.sh & install_full_stack()
          host: "gadi.nci.org.au"
          username: "rb5533"
          privateKey: ${{ secrets.GADI_PRIVATE_KEY}}
          passphrase: ${{ secrets.GADI_PRIVATE_KEY_PASSPHRASE}}
