name: tests

on: [push]

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - run: docker run --name underworld underworldcode/underworld2
      - run: docker exec -it underworld /bin/bash
      - run: python -c "import underworld as uw"